name: "Static Code Analysis"
on:
  push:
  pull_request:

env:
  TERRAFORM_VERSION: "0.15.0"
  PYTHON_VERSION: "3.x"

jobs:
  code_checks:
    name: "Static Code Analysis"
    runs-on: ubuntu-latest
    steps:
      # Pre Requisites
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cruft

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      # Run Static Code Analysis
      - name: Static Code Analysis
        run: make test-static-code-analysis
